public class Character {
    int strength;
    int agility;
    int intelligence;
    String name;
    public Object sayMyStrenght;

    public void sayMyName() {
        System.out.println("Hello I am " + name);
    
    
    }
    public void sayMyAgility(){
        System.out.println("My agility is " + agility);


    }
    public void sayMyIntelligence(){
        System.out.println("My Intelligence is " + intelligence);

    }
    
    public void sayMyStrength() {
        System.out.println("My strength is " + strength);
 


    }
}
